// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://olkkgjuysaxjwktoxijz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sa2tnanV5c2F4andrdG94aWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzAyNzcsImV4cCI6MjA3MDc0NjI3N30.P-ysKp-oOsyvRJPnz6JUtMwK6lTpGEWQZmIb-tj0OXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});